<a href='https://www.datacamp.com/cheat-sheet/numpy-cheat-sheet-data-analysis-in-python'> Numpy Cheat Sheet <a>

In [1]:
import numpy as np

One dimentional array:

In [4]:
#array of zeros:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Two dimensional array:

In [25]:
n = np.ones((3,3), dtype=int)
n

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [29]:
n[0][1]

1

Numpy Random: 

In [35]:
#Random numbers between 0-1 with uniform distributions
np.random.rand(5,2)

array([[0.42499037, 0.65875182],
       [0.4200356 , 0.33793004],
       [0.10576777, 0.24051275],
       [0.47327176, 0.64954209],
       [0.69651324, 0.75042945]])

In [40]:
#Random numbers between 0-1 with normal distributions
np.random.randn(5,2)

array([[-1.18643026, -0.58097578],
       [ 0.96636062,  1.2821765 ],
       [ 0.3276327 , -0.30755818],
       [-2.56289587,  0.69461623],
       [ 0.11150099, -0.19436963]])

In [39]:
#Random integer:
np.random.randint(low=0, high=5, size=(5,2))

array([[4, 1],
       [3, 2],
       [3, 2],
       [2, 3],
       [2, 1]])

Element-wise operations:

In [42]:
a = np.arange(10)

In [43]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
10*(a+10)

array([100, 110, 120, 130, 140, 150, 160, 170, 180, 190])

Comparison operators:

In [53]:
c =  np.random.randint(0, 5, (5,2))

In [51]:
b = np.random.randint(0, 5, (5,2))

In [52]:
b

array([[3, 1],
       [4, 0],
       [0, 4],
       [2, 2],
       [1, 0]])

In [55]:
c

array([[1, 0],
       [0, 3],
       [4, 1],
       [0, 1],
       [0, 0]])

In [57]:
b >= c

array([[ True,  True],
       [ True, False],
       [False,  True],
       [ True,  True],
       [ True,  True]])

In [63]:
b[b>2] # Select elements less than 2

array([3, 4, 4])

Summarizing operators:

In [58]:
b.min()

0

In [59]:
a.max()

9

In [60]:
c.sum()

10

In [61]:
c.std()

1.3416407864998738

In [62]:
b.mean()

1.7